### ISSUE TITLE
Update project with VCF

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#314]
Please edit this template:

**Describe the bug**
Update project with VCF

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create a project with VCF1 (see attached)
2. Update a project with VCF2 (see attached)
3. See error

Note:

**Expected behavior**
Updated project

**Screenshots**
![image](https://user-images.githubusercontent.com/40463532/142868283-8e347080-bb1f-43e3-8134-b279f53930f3.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version of Cutevariant: devel

**Additional context**

[STARK.20211120-220453.variants.Design.vcf.gz](https://github.com/labsquare/cutevariant/files/7581269/STARK.20211120-220453.variants.Design.vcf.gz)
[STARK.20211122-083219.variants.Design.vcf.gz](https://github.com/labsquare/cutevariant/files/7581272/STARK.20211122-083219.variants.Design.vcf.gz)

**Comment by antonylebechec** [comment]
Terminal error:

ERROR:[wizards/updatewizard.py:607:run()] unrecognized token: "1000genomesafr"
Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/wizards/updatewizard.py", line 587, in run
    for value, message in async_update_file(
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/importer.py", line 413, in async_update_file
    yield from async_update_reader(
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/importer.py", line 353, in async_update_reader
    insert_only_new_fields(conn, reader.get_fields())
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/sql.py", line 1131, in insert_only_new_fields
    cursor.execute(
sqlite3.OperationalError: unrecognized token: "1000genomesafr"
Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/wizards/updatewizard.py", line 608, in run
    raise e
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/wizards/updatewizard.py", line 587, in run
    for value, message in async_update_file(
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/importer.py", line 413, in async_update_file
    yield from async_update_reader(
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/importer.py", line 353, in async_update_reader
    insert_only_new_fields(conn, reader.get_fields())
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/sql.py", line 1131, in insert_only_new_fields
    cursor.execute(
sqlite3.OperationalError: unrecognized token: "1000genomesafr"
DEBUG:[wizards/updatewizard.py:775:thread_stop()] ImportPage:run: stop thread
TypeError: 'NoneType' object is not callable
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x6000004a4de0 'plugins'
DEBUG:[gui/plugin.py:178:on_close()] delete plugin... <widgets.FieldsEditorWidget(0x6000004f0b40, name="fields_editor") at 0x123dc5340>
DEBUG:[gui/plugin.py:180:on_close()] delete its dock...
