### ISSUE TITLE
Various errors in Plugin Documentation

### ISSUE THREAD

**Issue by ccarco** [labsquare/cutevariant#317]
Hi, 
I tried to add a plugin, following the instruction described in the [Wiki](https://github.com/labsquare/cutevariant/wiki/Plugins#plugin-directory-structure). So I create a directory in the "plugin" directory with the two files  ​__init__.py and widget.py :

 - The init.py file containing the mandatory variables :  `__title__`, `__description__` , `__author__` , `__version__`
 - The widget.py file containing the PluginWidget example ("FelixWidget")
 
However, when i run cutevariant, the following error appears :
        
        Traceback (most recent call last):
          File "C:\Users\ccarcopino\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
            return _run_code(code, main_globals, None,
          File "C:\Users\ccarcopino\Miniconda3\lib\runpy.py", line 87, in _run_code
            exec(code, run_globals)
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\__main__.py", line 238, in <module>
            main()
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\__main__.py", line 110, in main
            w = MainWindow()
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\gui\mainwindow.py", line 143, in __init__
            self.register_plugins()
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\gui\mainwindow.py", line 248, in register_plugins
            for extension in plugin.find_plugins():
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\gui\plugin.py", line 339, in find_plugins
            "long_description": module.__long_description__,
        AttributeError: module 'graphics' has no attribute '__long_description__'

When I add the `__long_description__` variable in the init.py file, the error is fixed.

But a new error appears when I run the script again : 

        Traceback (most recent call last):
          File "C:\Users\ccarcopino\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
            return _run_code(code, main_globals, None,
          File "C:\Users\ccarcopino\Miniconda3\lib\runpy.py", line 87, in _run_code
            exec(code, run_globals)
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\__main__.py", line 238, in <module>
            main()
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\__main__.py", line 110, in main
            w = MainWindow()
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\gui\mainwindow.py", line 143, in __init__
            self.register_plugins()
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\gui\mainwindow.py", line 248, in register_plugins
            for extension in plugin.find_plugins():
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\gui\plugin.py", line 370, in find_plugins
            sub_module = spec.loader.load_module()
          File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
          File "<frozen importlib._bootstrap_external>", line 1034, in load_module
          File "<frozen importlib._bootstrap_external>", line 859, in load_module
          File "<frozen importlib._bootstrap>", line 271, in _load_module_shim
          File "<frozen importlib._bootstrap>", line 613, in _exec
          File "<frozen importlib._bootstrap_external>", line 855, in exec_module
          File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\gui\plugins\graphics\widgets.py", line 4, in <module>
            class FelixWidget(plugin.PluginWidget):
          File "C:\Users\ccarcopino\Documents\repo\cutevariant\cutevariant\gui\plugins\graphics\widgets.py", line 5, in FelixWidget
            LOCATION = DOCK_LOCATION
        NameError: name 'DOCK_LOCATION' is not defined

To fix this error, you need to use plugin.DOCK_LOCATION instead of DOCK_LOCATION for the LOCATION variable

Python version : 3.9.5
OS : Windows
Installation of cutevariant : git clone
Branch : devel

**Comment by ccarco** [comment]
I will work on this issue if you're ok with it @dridk

**Comment by dridk** [comment]
the wiki is deprecated.  Check cutevariant.labsquare.org  for documentation. 
If you wish, you can update the wiki page
