### ISSUE TITLE
[Gene search] Bug when using "-" in gene name

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#332]
When using character "-" in gene name, the gene is not find.

List of all variants:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/40463532/155893197-5904340a-ef0a-4880-9563-c5fd529e3641.png">

When filtering with gene "WASH7P":
<img width="936" alt="image" src="https://user-images.githubusercontent.com/40463532/155893232-62ef45e0-210e-40ef-be4c-b113b439baaa.png">

When filtering with gene "MIR1302-2":
<img width="936" alt="image" src="https://user-images.githubusercontent.com/40463532/155893251-a5137a06-84bd-4d80-bfd9-c59df1c3f41b.png">
Apparently, SQL query is (gene name is cut on "-"):
DEBUG:[core/sql.py:332:<lambda>()] [SQLITE]: SELECT COUNT(*) as count FROM (SELECT DISTINCT `variants`.`id`,`variants`.`chr`,`annotations`.`gene` AS `ann.gene`,`variants`.`alt`,`variants`.`favorite`,`variants`.`pos`,`variants`.`ref`,`variants`.`classification` FROM variants LEFT JOIN annotations ON annotations.variant_id = variants.id WHERE (`annotations`.`gene` = 'MIR1302'))

Is it possible to use pattern ("*" or "%") in those cases? Such as:

- "MIR1302*"
- "*RAS" (for RAS genes family)
- "BBS*" (for BBS genes family)

Or better, a list of genes/variants such as:

- "*RAS *RAF" (for RAS and RAF genes family)

We can probably use "wordset" for this, but it is a quick search for exploring data "on the fly"...

**Comment by antonylebechec** [comment]
Moreover, is it possible to define other search fields?
Currently, only "annotations.gene" field is used. I suggest to use also by default "annotations.hgvs_c" and "annotations.hgvs_p", and the possibility to define others fields (preferences...), because it depend on each input VCF fields.

**Comment by antonylebechec** [comment]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/mainwindow.py", line 190, in <lambda>
    lambda: self.quick_search(self.quick_search_edit.text())
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/mainwindow.py", line 1202, in quick_search
    additionnal_filter = quicksearch(query)
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/quicksearch.py", line 33, in quicksearch
    parsed = strat(query)
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/quicksearch.py", line 126, in parse_vql_query
    res = parse_one_vql(f"SELECT chr,pos FROM variants WHERE {query}")
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/vql.py", line 357, in parse_one_vql
    return next(parse_vql(raw_vql))
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/vql.py", line 337, in parse_vql
    raise VQLSyntaxError(*error_message_from_err(err, raw_vql))
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/vql.py", line 99, in error_message_from_err
    raise err  # error not handled. Just raise it
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/vql.py", line 335, in parse_vql
    raw_model = METAMODEL.model_from_str(raw_vql)
  File "/usr/local/lib/python3.10/site-packages/textx/metamodel.py", line 497, in model_from_str
    model = self._parser.clone().get_model_from_str(
  File "/usr/local/lib/python3.10/site-packages/textx/model.py", line 279, in get_model_from_str
    self.parse(model_str, file_name=file_name)
  File "/usr/local/lib/python3.10/site-packages/arpeggio/__init__.py", line 1525, in parse
    self.parse_tree = self._parse()
  File "/usr/local/lib/python3.10/site-packages/textx/model.py", line 241, in _parse
    raise TextXSyntaxError(message=text(e),
textx.exceptions.TextXSyntaxError: None:1:42: error: Expected '[' or MathOperator at position (1, 42) => 'ERE CDKN2A*-DT'.
```
