### ISSUE TITLE
[gene view] Error when non gene/transcript field

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#371]
Please edit this template:

**Describe the bug**
When fields defined for gene and transcript, a bug appears and block cutevariant, especially refresh:
```
Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/plugins/variant_view/widgets.py", line 1608, in <lambda>
    lambda x, _: self.on_variant_clicked(x)
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/plugins/variant_view/widgets.py", line 1674, in on_variant_clicked
    self.mainwindow.refresh_plugins(self)
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/mainwindow.py", line 372, in refresh_plugins
    plugin.on_refresh()
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/plugins/gene_viewer/widgets.py", line 924, in on_refresh
    gene = self.current_variant["annotations"][0]["gene"]
IndexError: list index out of range
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create a project with a simple file (see attached)
2. See log

Note:
VCF example
[example.vcf.zip](https://github.com/labsquare/cutevariant/files/8459070/example.vcf.zip)

**Expected behavior**
No change on Gene viewer, or a warning message on the interface.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version of Cutevariant: devel

**Comment by antonylebechec** [comment]
Moreover, the configuration of gene/transcript is not enabled
