### ISSUE TITLE
[Export] fail VCF exporting, more suggestions

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#389]
When export in VCF:
```
DEBUG:[core/sql.py:2769:get_sample_annotations_by_variant()] SELECT sv.sample_id, sv.variant_id, samples.valid, samples.name , sv.gt FROM samples
    LEFT JOIN sample_has_variant sv
    ON sv.sample_id = samples.id AND sv.variant_id = 1
DEBUG:[core/sql.py:378:<lambda>()] [SQLITE]: SELECT sv.sample_id, sv.variant_id, samples.valid, samples.name , sv.gt FROM samples
    LEFT JOIN sample_has_variant sv
    ON sv.sample_id = samples.id AND sv.variant_id = 1
Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/export.py", line 246, in save
    success = self.save_from_writer(writer, "Exporting to VCF")
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/export.py", line 96, in save_from_writer
    for i in writer.async_save():
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/writer/vcfwriter.py", line 184, in async_save
    ssample = self.get_samples_column(variant["id"])
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/core/writer/vcfwriter.py", line 121, in get_samples_column
    ssample.append(VcfWriter.GENOTYPE_MAP[ann.get("gt", "")])
KeyError: None
```

<img width="429" alt="image" src="https://user-images.githubusercontent.com/40463532/164914592-c0593d47-97cf-4ac4-8436-590d58b4362b.png">

I suspect also that "classification" (favorite, classification, tags...) are badly exported.

Is it possible to export as tab-delimited file?

PED export should consider also other samples' columns, such as tags, valid, comment, HPO...

**Comment by antonylebechec** [comment]
Fix export VCF
TODO:
- Export only samples in "validation" widget
- Export all fields of samples for export PED
- Fix list of fields that will be exported (remove favorite, classification...), or and an option to export these fields (for specific export of classification/valid infos on variant/sample_has_variant resp.)

**Comment by antonylebechec** [comment]
solved
