### ISSUE TITLE
install fails on mac using conda

### ISSUE THREAD

**Issue by splaisan** [labsquare/cutevariant#570]
Hi,

-working on a mac with catalina 10.15.7
-conda 4.12.0

I prefer to use conda to virtenv to compartimentize my installs and it usually works.
I therefore created a conda env with python 3.9 in which I installed cutevariant with pip without error messages
when I start cutevariant (latest or dev), I get the error below, can you please tell me what I need to install to fix this?
I tried installing qt (5.15.19) with conda but it did not improve.

Thanks for your help

Stephane

## conda create

```
(base)  $ conda create -n cutevariant python=3.9

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/miniconda3/envs/cutevariant

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2022.10.11-hecd8cb5_0
  certifi            pkgs/main/osx-64::certifi-2022.9.24-py39hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-14.0.6-h9765a3e_0
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.3-hca72f7f_3
  openssl            pkgs/main/osx-64::openssl-1.1.1q-hca72f7f_0
  pip                pkgs/main/osx-64::pip-22.2.2-py39hecd8cb5_0
  python             pkgs/main/osx-64::python-3.9.13-hdfd78df_2
  readline           pkgs/main/osx-64::readline-8.2-hca72f7f_0
  setuptools         pkgs/main/osx-64::setuptools-63.4.1-py39hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.39.3-h707629a_0
  tk                 pkgs/main/osx-64::tk-8.6.12-h5d9f67b_0
  tzdata             pkgs/main/noarch::tzdata-2022e-h04d1e81_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.6-hca72f7f_0
  zlib               pkgs/main/osx-64::zlib-1.2.13-h4dc903c_0


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate cutevariant
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

## conda activate & install

```
(base)  $ conda activate cutevariant

(cutevariant) $ python -m pip install cutevariant
Collecting cutevariant
  Using cached cutevariant-0.4.4-py3-none-any.whl (1.2 MB)
Collecting cachetools>=4.2.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting jinja2>=2.11.3
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting markdown
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Collecting textX==1.8.0
  Using cached textX-1.8.0-py2.py3-none-any.whl (51 kB)
Collecting numpy>=1.20
  Using cached numpy-1.23.4-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)
Collecting columnar==1.1.0
  Using cached Columnar-1.1.0-py3-none-any.whl (8.4 kB)
Collecting pyyaml>=5.4.0
  Using cached PyYAML-6.0-cp39-cp39-macosx_10_9_x86_64.whl (197 kB)
Collecting PySide6>=2
  Using cached PySide6-6.4.0.1-cp37-abi3-macosx_10_9_universal2.whl (6.9 kB)
Collecting PyVCF3>=1.0.0
  Using cached PyVCF3-1.0.3-py3-none-any.whl
Collecting progressbar2
  Using cached progressbar2-4.2.0-py2.py3-none-any.whl (27 kB)
Collecting toolz
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting Arpeggio>=1.9.0
  Using cached Arpeggio-2.0.0-py2.py3-none-any.whl (54 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp39-cp39-macosx_10_9_x86_64.whl (13 kB)
Collecting shiboken6==6.4.0.1
  Using cached shiboken6-6.4.0.1-cp37-abi3-macosx_10_9_universal2.whl (322 kB)
Collecting PySide6-Addons==6.4.0.1
  Using cached PySide6_Addons-6.4.0.1-cp37-abi3-macosx_10_9_universal2.whl (218.3 MB)
Collecting PySide6-Essentials==6.4.0.1
  Using cached PySide6_Essentials-6.4.0.1-cp37-abi3-macosx_10_9_universal2.whl (140.9 MB)
Requirement already satisfied: setuptools in /opt/miniconda3/envs/cutevariant/lib/python3.9/site-packages (from PyVCF3>=1.0.0->cutevariant) (63.4.1)
Collecting importlib-metadata>=4.4
  Using cached importlib_metadata-5.0.0-py3-none-any.whl (21 kB)
Collecting python-utils>=3.0.0
  Using cached python_utils-3.3.3-py2.py3-none-any.whl (23 kB)
Collecting zipp>=0.5
  Using cached zipp-3.10.0-py3-none-any.whl (6.2 kB)
Installing collected packages: Arpeggio, zipp, toolz, textX, shiboken6, pyyaml, PyVCF3, python-utils, numpy, MarkupSafe, cachetools, PySide6-Essentials, progressbar2, jinja2, importlib-metadata, columnar, PySide6-Addons, markdown, PySide6, cutevariant
Successfully installed Arpeggio-2.0.0 MarkupSafe-2.1.1 PySide6-6.4.0.1 PySide6-Addons-6.4.0.1 PySide6-Essentials-6.4.0.1 PyVCF3-1.0.3 cachetools-5.2.0 columnar-1.1.0 cutevariant-0.4.4 importlib-metadata-5.0.0 jinja2-3.1.2 markdown-3.4.1 numpy-1.23.4 progressbar2-4.2.0 python-utils-3.3.3 pyyaml-6.0 shiboken6-6.4.0.1 textX-1.8.0 toolz-0.12.0 zipp-3.10.0
```

## run

```
(cutevariant) $ python -m cutevariant 
/opt/biotools/cutevariant/source/cutevariant/__main__.py:67: DeprecationWarning: Enum value 'Qt::ApplicationAttribute.AA_EnableHighDpiScaling' is marked as deprecated, please check the documentation for more information.
  QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
/opt/biotools/cutevariant/source/cutevariant/__main__.py:69: DeprecationWarning: Enum value 'Qt::ApplicationAttribute.AA_UseHighDpiPixmaps' is marked as deprecated, please check the documentation for more information.
  QCoreApplication.setAttribute(Qt.AA_UseHighDpiPixmaps, True)
Traceback (most recent call last):
  File "/opt/miniconda3/envs/cutevariant/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/cutevariant/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/biotools/cutevariant/source/cutevariant/__main__.py", line 253, in <module>
    main()
  File "/opt/biotools/cutevariant/source/cutevariant/__main__.py", line 80, in main
    load_styles(app)
  File "/opt/biotools/cutevariant/source/cutevariant/__main__.py", line 162, in load_styles
    mystyle = style.AppStyle()
  File "/opt/biotools/cutevariant/source/cutevariant/gui/style.py", line 27, in __init__
    AppStyle.PALETTE_KEYS = {camel_to_snake(k): v for k, v in QPalette.ColorRole.values.items()}
  File "/opt/miniconda3/envs/cutevariant/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: values
```
# conda installed

```
(cutevariant) $ conda list
# packages in environment at /opt/miniconda3/envs/cutevariant:
#
# Name                    Version                   Build  Channel
arpeggio                  2.0.0                    pypi_0    pypi
ca-certificates           2022.10.11           hecd8cb5_0  
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.9.24        py39hecd8cb5_0  
columnar                  1.1.0                    pypi_0    pypi
cutevariant               0.4.4                    pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
libcxx                    14.0.6               h9765a3e_0  
libffi                    3.3                  hb1e8313_2  
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
ncurses                   6.3                  hca72f7f_3  
numpy                     1.23.4                   pypi_0    pypi
openssl                   1.1.1q               hca72f7f_0  
pip                       22.2.2           py39hecd8cb5_0  
progressbar2              4.2.0                    pypi_0    pypi
pyside6                   6.4.0.1                  pypi_0    pypi
pyside6-addons            6.4.0.1                  pypi_0    pypi
pyside6-essentials        6.4.0.1                  pypi_0    pypi
python                    3.9.13               hdfd78df_2  
python-utils              3.3.3                    pypi_0    pypi
pyvcf3                    1.0.3                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  hca72f7f_0  
setuptools                63.4.1           py39hecd8cb5_0  
shiboken6                 6.4.0.1                  pypi_0    pypi
sqlite                    3.39.3               h707629a_0  
textx                     1.8.0                    pypi_0    pypi
tk                        8.6.12               h5d9f67b_0  
toolz                     0.12.0                   pypi_0    pypi
tzdata                    2022e                h04d1e81_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.6                hca72f7f_0  
zipp                      3.10.0                   pypi_0    pypi
zlib                      1.2.13               h4dc903c_0  
```

**Comment by dridk** [comment]
@antonylebechec could you try to reproduce this bug?

**Comment by splaisan** [comment]
Thanks @dridk, I added the package list as installed now if that helps
Maybe some of my packages are too recent?

**Comment by dridk** [comment]
Ok, I get the same error on Linux.

**Comment by dridk** [comment]
@splaisan Could you try my fix ? By the way, I m curious to see if it works from conda.  

```
pip install git+https://github.com/labsquare/cutevariant@devel
```

**Comment by splaisan** [comment]
I created a new env and installed as above except I used your dev target.
It now started OK without complaining about anything and I will import some chicken data in it to see how the beast does the work.
conda seems to do the job ;-)

```
conda create -n cutevariant_dev python=3.9
conda activate cutevariant_dev
pip install git+https://github.com/labsquare/cutevariant@devel
python -m cutevariant

```
thanks a lot Sacha for your quick fix, I will post on progresses

**Comment by dridk** [comment]
ok ! 
Please give us any feedback to improve the software. We are far away from the perfect software. So, any feedback are  very important for us.

**Comment by splaisan** [comment]
thanks Sacha, will do
btw: same also works under ubuntu on my remote server

**Comment by antonylebechec** [comment]
Sorry for the late reply.
The devel branch work on my MacOS. Installation is ok, and cutevariant is launched correctly.
Thanks Sacha!
