### ISSUE TITLE
Can't run - Error on absolute path of a database...

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#7]
Here the stacktrace:

```
QObject::connect: No such slot MainWindow::open_project()
Traceback (most recent call last):
  File "/home/Lex/.virtualenvs/native_messaging/bin/cutevariant", line 11, in <module>
    load_entry_point('cutevariant', 'console_scripts', 'cutevariant')()
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/__main__.py", line 11, in main
    w = MainWindow()
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/mainwindow.py", line 67, in __init__
    self.addPanel(HpoQueryWidget())
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/hpoquerywidget.py", line 187, in __init__
    conn =  sqlite3.connect("/home/schutz/Dev/hpo2sqlite/hpo.db")
sqlite3.OperationalError: unable to open database file
```

**Comment by ysard** [comment]
Fixed in f153a49
